"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  exportAiBrief,
  importAiOutput,
  getPlanImportState,
  type ImportMode,
  type MonthlyPlanReadiness,
  type PlanImportState,
} from "@/lib/actions/monthly-plans";
import { Modal } from "@/components/ui/Modal";
import { periodMonthLabel } from "@/lib/monthly-plan-format";
import { Button } from "@/components/ui/Button";
import { Textarea } from "@/components/ui/Input";
import { Notice } from "@/components/ui/Notice";

/**
 * The first AI workflow (Duane, 5 Sep 2026): no Claude API here. Generate a
 * brief, a person pastes it into Claude by hand, pastes the JSON that comes
 * back in below. PBOS validates and creates the rows itself — Claude never
 * writes to the database directly.
 *
 * `readiness` gates generation (Duane, testing Daniel's October plan): PBOS
 * must not generate off incomplete client intelligence — exportAiBrief
 * itself refuses too, this just says so before anyone clicks the button.
 */
export function AiBriefPanel({
  clientId,
  planId,
  periodMonth,
  readiness,
}: {
  clientId: string;
  planId: string;
  periodMonth: string;
  readiness: MonthlyPlanReadiness;
}) {
  const [brief, setBrief] = useState<string | null>(null);
  const [briefError, setBriefError] = useState<string | null>(null);
  const [isGenerating, startGenerate] = useTransition();
  const [copied, setCopied] = useState(false);

  const [pasted, setPasted] = useState("");
  const [importError, setImportError] = useState<string | null>(null);
  const [importSummary, setImportSummary] = useState<string | null>(null);
  const [importWarnings, setImportWarnings] = useState<string[]>([]);
  const [isImporting, startImport] = useTransition();
  /** Set when the plan already holds imported content — the Replace / Add /
   * Cancel decision (Duane) is made here, never assumed. */
  const [decision, setDecision] = useState<PlanImportState | null>(null);
  const router = useRouter();

  function generate() {
    setBriefError(null);
    startGenerate(async () => {
      const result = await exportAiBrief(clientId, planId);
      if (!result.ok) {
        setBriefError(result.message);
        return;
      }
      setBrief(result.data.brief);
    });
  }

  function copyBrief() {
    if (!brief) return;
    navigator.clipboard
      .writeText(brief)
      .then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      })
      .catch(() => setBriefError("Couldn't copy — your browser blocked clipboard access."));
  }

  function runImport() {
    setImportError(null);
    setImportSummary(null);
    setImportWarnings([]);
    startImport(async () => {
      const state = await getPlanImportState(clientId, planId);
      if (!state.ok) {
        setImportError(state.message);
        return;
      }
      if (state.data.closed) {
        setImportError("This Monthly Plan is closed — set it back to Planning or In review before importing.");
        return;
      }
      if (state.data.replaceable + state.data.locked > 0) {
        setDecision(state.data);
        return;
      }
      await doImport("add");
    });
  }

  async function doImport(mode: ImportMode) {
    setDecision(null);
    const result = await importAiOutput(clientId, planId, pasted, mode);
    if (!result.ok) {
      setImportError(result.message);
      return;
    }
    const { replaced, kept, revisionCreated, masterContentCreated, platformOutputsCreated, requirementsAutoGenerated, datesAssigned, warnings } =
      result.data;
    setImportSummary(
      (revisionCreated !== null ? `Saved the previous plan as revision ${revisionCreated} and set this one back to In review. ` : "") +
        (replaced > 0 ? `Replaced ${replaced} draft item(s)${kept > 0 ? ` (${kept} kept)` : ""}. ` : "") +
        `Imported ${masterContentCreated} Master Content, ${platformOutputsCreated} Platform Output(s)` +
        (requirementsAutoGenerated > 0 ? `, ${requirementsAutoGenerated} Requirement(s) auto-generated` : "") +
        `, and assigned publish dates to ${datesAssigned} output(s).`
    );
    setImportWarnings(warnings);
    setPasted("");
    router.refresh();
  }

  function chooseMode(mode: ImportMode) {
    startImport(async () => {
      await doImport(mode);
    });
  }

  return (
    <div className="space-y-4 rounded-lg border border-border bg-surface p-4">
      {!readiness.ready && (
        <Notice kind="danger">
          <p className="font-medium">Monthly Plan not ready</p>
          <ul className="mt-1 list-disc space-y-0.5 pl-4">
            {readiness.blockers.map((b, i) => (
              <li key={i}>{b}</li>
            ))}
          </ul>
          <p className="mt-2 text-xs">
            Complete these on the client&rsquo;s Content Guidelines or Social tab, then refresh this page.
          </p>
        </Notice>
      )}
      <div>
        <h3 className="text-sm font-semibold text-ink">1. Generate the AI brief</h3>
        <p className="mt-1 text-xs text-ink-soft">
          Client context from this plan&rsquo;s Client Snapshot, plus the exact JSON shape to return. Paste the whole thing
          into Claude.
        </p>
        <div className="mt-2 flex items-center gap-2">
          <Button variant="secondary" size="sm" onClick={generate} disabled={isGenerating || !readiness.ready}>
            {isGenerating ? "Generating…" : brief ? "Regenerate brief" : "Generate brief"}
          </Button>
          {brief && (
            <Button variant="ghost" size="sm" onClick={copyBrief}>
              {copied ? "Copied ✓" : "Copy brief"}
            </Button>
          )}
        </div>
        {briefError && <Notice kind="danger">{briefError}</Notice>}
        {brief && <Textarea readOnly rows={10} value={brief} className="mt-2 font-mono text-xs" onFocus={(e) => e.currentTarget.select()} />}
      </div>

      <div className="border-t border-border pt-4">
        <h3 className="text-sm font-semibold text-ink">2. Import Claude&rsquo;s JSON</h3>
        <p className="mt-1 text-xs text-ink-soft">
          Paste exactly what Claude returned. Nothing is written until you click Import — every pillar, audience and
          platform id is checked against this client&rsquo;s real records first, and the whole import is rejected
          (nothing written) if any don&rsquo;t match. If this plan already has imported content you&rsquo;ll be asked
          whether to replace its draft content or add alongside it.
        </p>
        <Textarea
          rows={8}
          value={pasted}
          onChange={(e) => setPasted(e.target.value)}
          placeholder='{"master_content": [...], "platform_outputs": [...]}'
          className="mt-2 font-mono text-xs"
        />
        <div className="mt-2 flex items-center gap-2">
          <Button variant="primary" size="sm" onClick={runImport} disabled={isImporting || !pasted.trim()}>
            {isImporting ? "Importing…" : "Import AI output"}
          </Button>
        </div>
        {importError && (
          <Notice kind="danger">
            <pre className="whitespace-pre-wrap font-sans text-xs">{importError}</pre>
          </Notice>
        )}
        {importSummary && <Notice kind="success">{importSummary}</Notice>}
        {decision && (
          <Modal title={`${periodMonthLabel(periodMonth)} already has imported content`} onClose={() => setDecision(null)}>
            <div className="space-y-3 text-sm text-ink-soft">
              <p>
                This plan holds <strong className="text-ink">{decision.replaceable + decision.locked}</strong> AI-imported Master Content
                ({decision.replaceable} draft{decision.locked > 0 ? `, ${decision.locked} approved / scheduled / published` : ""}
                {decision.manual > 0 ? `, plus ${decision.manual} added by hand` : ""}). What should this import do?
              </p>
              <div className="space-y-2">
                {/* First button in the DOM takes focus — Replace is the default. */}
                <button
                  type="button"
                  onClick={() => chooseMode("replace")}
                  disabled={isImporting || decision.replaceable === 0}
                  className="block w-full rounded-md border border-accent bg-accent/10 px-3 py-2 text-left hover:bg-accent/20 disabled:opacity-50"
                >
                  <span className="block font-medium text-ink">
                    {decision.requiresRevision
                      ? `Create revision ${decision.revision + 1} and replace draft content`
                      : "Replace existing draft content"}
                  </span>
                  <span className="block text-xs">
                    {decision.requiresRevision
                      ? `Saves the current approved plan as revision ${decision.revision}, removes the ${decision.replaceable} draft item(s) and their Platform Outputs, imports this, and sets the plan back to In review.`
                      : `Removes the ${decision.replaceable} draft item(s) and their Platform Outputs from this plan only, then imports this.`}
                    {decision.locked + decision.manual > 0 ? " Approved, scheduled, published and hand-added content is never touched." : ""}
                  </span>
                </button>
                <button
                  type="button"
                  onClick={() => chooseMode("add")}
                  disabled={isImporting}
                  className="block w-full rounded-md border border-border bg-surface px-3 py-2 text-left hover:bg-surface-muted disabled:opacity-50"
                >
                  <span className="block font-medium text-ink">Add as new</span>
                  <span className="block text-xs">Keeps everything already on the plan and numbers the new Master Content after it.</span>
                </button>
                <button
                  type="button"
                  onClick={() => setDecision(null)}
                  disabled={isImporting}
                  className="block w-full rounded-md px-3 py-2 text-left text-ink-soft hover:bg-surface-muted"
                >
                  Cancel
                </button>
              </div>
            </div>
          </Modal>
        )}
        {importWarnings.length > 0 && (
          <Notice kind="info">
            <ul className="list-disc space-y-0.5 pl-4">
              {importWarnings.map((w, i) => (
                <li key={i}>{w}</li>
              ))}
            </ul>
          </Notice>
        )}
      </div>
    </div>
  );
}
